Feature/first version
William-Hill-Online/trivy-wrapper-api pull request #1
Opened 2020-09-03 16:12 UTC by edersonbrilhante

## Description
This PR will create the first version of the wrapper

## How test
### Running locally
```
docker-compose -f docker/docker-compose.yaml up
```
### Executing test
#### Running using curl
```curl --location --request POST 'http://localhost:8080/analysis' \
--header 'Content-Type: application/json' \
--data-raw '
{"image":"alpine:3.1"}'
```
#### Result expected
```
{
    "error": "",
    "result": [
        {
            "Target": "alpine:3.1 (alpine 3.1.4)",
            "Type": "alpine",
            "Vulnerabilities": null
        }
    ],
    "success": true
}
```

2020-09-18 06:50 UTC, szymonwyrwiak reviewed
Was wondering about adding 

```
# ====================================================================
# See https://pre-commit.com              for more information
# See https://pre-commit.com/hooks.html   for more hooks
# ====================================================================
```
to the top.

2020-09-18 07:00 UTC, szymonwyrwiak reviewed
go-lint needs separate installation through 
`go get -u golang.org/x/lint/golint`
without it
`pre-commit run --all-files` 
will fail with message like
`go lint..................................................................Failed
hook id: go-lint
exit code: 1
/Users/user/.cache/pre-commit/repoetk6vpau/run-go-lint.sh: line 7: golint: command not found`

2020-09-18 07:13 UTC, szymonwyrwiak reviewed
We have to add informations about:

- Usage
-- How to run server
-- How to consume APIs

later one

2020-09-18 13:05 UTC, szymonwyrwiak requested changes

2020-09-18 13:43 UTC, edersonbrilhante commented on api/analysis/analysis.go
> +	remoteTrivy := os.Getenv("REMOTE_TRIVY")
`REMOTE_TRIVY` is the IP + port running the `trivy_server`. If you change the IP and port of `trivy_server`, you have to change the value in ENVVAR `REMOTE_TRIVY` with the new IP and port.

2020-09-18 13:49 UTC, edersonbrilhante commented on api/routes/healthcheck.go
> +// license that can be found in the LICENSE file.
Good catch. I copied the license block as example and I forgot to change :)

2020-09-18 13:55 UTC, edersonbrilhante commented on go.mod
> +	github.com/sirupsen/logrus v1.6.0
This is normal. Each dep in go.mod has more deps, so go.sum list all deps needed. You will have the same in projects in python or javascript

2020-09-18 13:58 UTC, edersonbrilhante commented on README.md
> +```
Do you think the curl in the description in this MR could be enough?

2020-09-18 14:01 UTC, edersonbrilhante commented on docker/docker-compose.yaml
> +    trivy_net:
This docker-compose is just to help the development. So the server and the API can be started easily for development purposes

2020-09-18 14:16 UTC, edersonbrilhante commented on .pre-commit-config.yaml
> +repos:
Done

2020-09-18 14:27 UTC, edersonbrilhante commented
> We should add test coverage later one.

Agreed.

2020-09-21 10:35 UTC, szymonwyrwiak approved these changes
LGTM

2020-09-24 10:31 UTC, szymonwyrwiak commented on README.md
> +```
For mvp it's enough

2020-09-24 13:40 UTC, merged